development:
  adapter: postgresql
  encoding: utf8
  database: flittr_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: flittr_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: flittr_production
  pool: 5
  host: localhost
